version: "2.0"
services:
        web:
                build: .
                ports:
                        - "80:5000"
                        - "8025:8025"
                volumes:
                        - /home/ubuntu/Ulifestyle/ulifestyle_folder:/root
