"""author table

Revision ID: 112872f9c662
Revises: d75050d26d16
Create Date: 2020-04-30 18:51:49.245144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112872f9c662'
down_revision = 'd75050d26d16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('usergroup', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_username'), 'author', ['username'], unique=True)
    op.create_foreign_key(None, 'post', 'author', ['author'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_index(op.f('ix_author_username'), table_name='author')
    op.drop_table('author')
    # ### end Alembic commands ###
