"""carousel table

Revision ID: 1d4e17143c9a
Revises: 112e9943c5ef
Create Date: 2020-05-03 20:30:24.465063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d4e17143c9a'
down_revision = '112e9943c5ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carousel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('img', sa.String(length=200), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carousel_img'), 'carousel', ['img'], unique=False)
    op.create_index(op.f('ix_carousel_link'), 'carousel', ['link'], unique=False)
    op.create_index(op.f('ix_carousel_title'), 'carousel', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carousel_title'), table_name='carousel')
    op.drop_index(op.f('ix_carousel_link'), table_name='carousel')
    op.drop_index(op.f('ix_carousel_img'), table_name='carousel')
    op.drop_table('carousel')
    # ### end Alembic commands ###
