"""users table

Revision ID: 6821f75f7968
Revises: 
Create Date: 2020-12-10 18:21:16.769688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6821f75f7968'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('usergroup', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_username'), 'author', ['username'], unique=True)
    op.create_table('carousel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('img', sa.String(length=200), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carousel_img'), 'carousel', ['img'], unique=False)
    op.create_index(op.f('ix_carousel_link'), 'carousel', ['link'], unique=False)
    op.create_index(op.f('ix_carousel_title'), 'carousel', ['title'], unique=False)
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contype', sa.String(), nullable=True),
    sa.Column('conway', sa.String(), nullable=True),
    sa.Column('phoneno', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('hyperlink', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mediaapp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mediatype', sa.String(), nullable=True),
    sa.Column('hyperlink', sa.String(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_tag'), 'tag', ['tag'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('phoneNumber', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('educationLevel', sa.String(length=30), nullable=True),
    sa.Column('income', sa.String(length=30), nullable=True),
    sa.Column('usergroup', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=30), nullable=False),
    sa.Column('getinfo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('beautypost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=30), nullable=True),
    sa.Column('body1', sa.String(length=100), nullable=True),
    sa.Column('body2', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('theme', sa.String(length=10), nullable=True),
    sa.Column('tag', sa.String(length=10), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['author.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beautypost_timestamp'), 'beautypost', ['timestamp'], unique=False)
    op.create_table('foodpost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=30), nullable=True),
    sa.Column('body1', sa.String(length=100), nullable=True),
    sa.Column('body2', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('theme', sa.String(length=10), nullable=True),
    sa.Column('tag', sa.String(length=10), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['author.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foodpost_timestamp'), 'foodpost', ['timestamp'], unique=False)
    op.create_table('hkpost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=30), nullable=True),
    sa.Column('body1', sa.String(length=100), nullable=True),
    sa.Column('body2', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('theme', sa.String(length=10), nullable=True),
    sa.Column('tag', sa.String(length=10), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['author.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hkpost_timestamp'), 'hkpost', ['timestamp'], unique=False)
    op.create_table('travelpost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=30), nullable=True),
    sa.Column('body1', sa.String(length=100), nullable=True),
    sa.Column('body2', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('theme', sa.String(length=10), nullable=True),
    sa.Column('tag', sa.String(length=10), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['author.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travelpost_timestamp'), 'travelpost', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_travelpost_timestamp'), table_name='travelpost')
    op.drop_table('travelpost')
    op.drop_index(op.f('ix_hkpost_timestamp'), table_name='hkpost')
    op.drop_table('hkpost')
    op.drop_index(op.f('ix_foodpost_timestamp'), table_name='foodpost')
    op.drop_table('foodpost')
    op.drop_index(op.f('ix_beautypost_timestamp'), table_name='beautypost')
    op.drop_table('beautypost')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tag_tag'), table_name='tag')
    op.drop_table('tag')
    op.drop_table('mediaapp')
    op.drop_table('contact')
    op.drop_index(op.f('ix_carousel_title'), table_name='carousel')
    op.drop_index(op.f('ix_carousel_link'), table_name='carousel')
    op.drop_index(op.f('ix_carousel_img'), table_name='carousel')
    op.drop_table('carousel')
    op.drop_index(op.f('ix_author_username'), table_name='author')
    op.drop_table('author')
    # ### end Alembic commands ###
