"""post form rebuild

Revision ID: 82bf13a1d1ee
Revises: cf09525c0ee2
Create Date: 2020-05-02 23:35:18.471855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82bf13a1d1ee'
down_revision = 'cf09525c0ee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('site', sa.String(length=30), nullable=True))
    op.alter_column('post', 'body1',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('post', 'tag',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('post', 'theme',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['author'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'author', ['author'], ['username'])
    op.alter_column('post', 'theme',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('post', 'tag',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('post', 'body1',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('post', 'site')
    # ### end Alembic commands ###
