"""video post table

Revision ID: c9ec9a8d72ed
Revises: 6821f75f7968
Create Date: 2020-12-10 20:17:38.122052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9ec9a8d72ed'
down_revision = '6821f75f7968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hkvideopost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=30), nullable=True),
    sa.Column('body1', sa.String(length=100), nullable=True),
    sa.Column('video', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['author.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hkvideopost_timestamp'), 'hkvideopost', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hkvideopost_timestamp'), table_name='hkvideopost')
    op.drop_table('hkvideopost')
    # ### end Alembic commands ###
